### ISSUE TITLE
Make header and nav menu 'sticky'

### ISSUE THREAD

**Issue by mike99christie** [u3a-siteworks-development/u3a-siteworks-theme#6]
This would mean that the nav menu always stayed visible when a user scrolls down the webpage.
To achieve this the header template part must be inside a top-level group block and the group block has the attribute 'sticky'.

We would have to edit all the theme's templaytes that include the header block to put them inside a block.
Ideally we'd make this an option that a u3a could choose, but I don't know how to achieve that.
Views?

**Comment by edwery** [comment]
Its an interesting trade-off. Right now I have 17cm of usable screen height, of which firefox takes 4cm and the u3a title takes 3cm, leaving me 10 cm of height - just enough for half a photo or a paragraph of text.
I do like the idea of having the menu permanently available, but think it might need to be a u3a config option available to the web designer.

**Comment by stratplusft** [comment]
I've started looking at this on the latest download with WordPress 6.2.5 . Looking at the comments in the Forum, the navigation menu can be made sticky using the plug in "Sticky Block for Gutenberg Editor", which offers a Stick Block which can be added and used to contain the elements that are to be sticky. The block options allow the z-index to be set so that the sticky element doesn't disappear behind other elements. I found a value of 100 worked for me, but it depends which other elements are on the page.
I agree that we don't want too many non u3a plugins, but so far I haven't found another way to make the nav bar sticky despite various "sticky" settings being available on the blocks.

**Comment by nicktrosnant** [comment]
Thanks for the feedback, Bill.  I've also used the Sticky Block for Gutenberg Editor and it does the job fine.  Demo video here: https://drive.google.com/file/d/1kO4WXC-lp5OKAMns4-fjjLpgBDpr-lm8/view?usp=sharing

Looking at the page code generated when you wrap the navigation row in a Sticky block, there are two elements coming into play.  There is the css provided by the block (blocks.style.build.css) and then there is a JavaScript file (sticky_block..js).  I've not worked out exactly what the JavaScript is doing but it appears to be hooking into the page scrolling and altering classes on the sticky div dynamically.  It also appears to insert at least one additional hidden div before the sticky div .  Complex stuff!

**Comment by stratplusft** [comment]
I haven't worked out exactly what the JS does either. I see from the notes that it is based on Sticky Menu (or Anything) plug in. Presumably the open source licence allows that. I guess if someone wanted to write a u3a plugin based on it to suit our requirements then that would be possible, but I don't think I would want to do it. My inclination at the moment is to recommend "Sticky Block for Gutenberg Editor" for those requiring the sticky menu. The notes with it are simple to follow. I suppose the question would be would we assist anyone who needs help with it?
I also used the WordPress sticky to make the whole header sticky. That is certainly easy to do, but it looks rather clunky to me.

**Comment by mike99christie** [comment]
I've just come across an awkward effect produced on the nlu3a test site for our planned use of Siteworks.
We have a one row header which contains the nav menu, and it is in a top level group which is 'sticky'. That works fine, but if you get to the list of groups and then click on any of the buttons e.g.
[(http://nlu3a-demo.christiex.uk/groups-list/?sort=alpha#list_button_anchor)]
you will see the list but not see the buttons.  They are hidden by the sticky nav menu, as the scrolling mechanism isn't smart enough to know that the menu doesn't count when scrolling to an anchor.
Oops.
I'd like to turn off the feature that scrolls down the page, as our group list is the only item on the page.
Hmm.
Solutions please!

**Comment by nicktrosnant** [comment]
This can either be achieved by using the WordPress  'Position -> Sticky' property setting on a top-level block, or by using a plugin such as [Sticky Block for Gutenberg Editor](https://wordpress.org/plugins/sticky-block/)

**Comment by nicktrosnant** [comment]
This can either be achieved by using the WordPress  'Position -> Sticky' property setting on a top-level block, or by using a plugin such as [Sticky Block for Gutenberg Editor](https://wordpress.org/plugins/sticky-block/)
