### ISSUE TITLE
Make scrolling smooth when jumping to a link further down the page

### ISSUE THREAD

**Issue by mike99christie** [u3a-siteworks-development/u3a-siteworks-theme#7]
Occasionally a u3a may tag a block with an "HTML ANCHOR" and then this can be used as link elsewhere on the page. When clicking the browser will either jump to the marked tag or scroll smoothly down, which I think is preferable.
The following css achieves this.
html { scroll-behavior: smooth;}
How about adding it to the theme's css file?

**Comment by CamillaJordan** [comment]
I actually prefer the jump - particularly if it is far down the page but it is not a big issue as far as I am concerned.

**Comment by mike99christie** [comment]
We have decided not to implement this.
